# Generated by Django 5.0.3 on 2024-03-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='products')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('cliente', 'Client'), ('empleado', 'Empleado')], default='cliente', max_length=20),
        ),
    ]
